name: "Build and release application"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: "v1"

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ${{matrix.envCmd.os}}

    strategy:
      matrix:
        envCmd:
          - {os: "windows-latest", buildCmd: "npm run dist:win"}
          # - {os: "ubuntu-latest", buildCmd: "npm run dist:linux"}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: setup js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Debug: JS version"
        run: node --version

      - name: install dependency
        run: npm i
      
      - name: build app
        run: ${{matrix.envCmd.buildCmd}}

      - name: debug
        run: |
          ls
          ls release
          ls release/win-unpacked

      - name: realse app
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release/win-unpacked/FloatNote.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            
