name: "Build and release application"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        default: "v1"

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ${{matrix.envCmd.os}}

    strategy:
      matrix:
        envCmd:
          - {os: "windows-latest", buildCmd: "npm run dist:win"}
          # - {os: "ubuntu-latest", buildCmd: "npm run dist:linux"}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Debug: Node version"
        run: node --version

      - name: Install dependencies
        run: npm i

      - name: Build app
        run: ${{matrix.envCmd.buildCmd}}

      - name: Debug release output
        run: |
          ls release

      - name: Release app
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            release/*Setup*.exe
            release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
